### ISSUE TITLE
Implement way to receive and parse GPS data from smartphone

### ISSUE THREAD

**Issue by s-sparrow** [Uvic-Robotics-Club/Shell#10]
***What***: Receive GPS data from the smartphone, identify and parse its values, and store it as JSON.

***Why***: So that we have the GPS data in an appropriate structure that will be sent to the base station (which will be done in a future issue).

***Where***: Create a branch and put code in a 'Smartphone' directory in the Scheduler.

***Subtasks***:
- [x] Set up smartphone to send data to laptop
- [x] Receive data from smartphone
- [x] Identify the data (eg. which value is latitude)
- [x] Use a JSON library to turn data into JSON
- [x] Create a README.md file in the Smartphone directory.
- [x] Add smartphone model and app name to readme
- [x] Add smartphone app setup instructions to readme
