### ISSUE TITLE
Implement way to identify and communicate with microcontrollers

### ISSUE THREAD

**Issue by s-sparrow** [Uvic-Robotics-Club/Shell#13]
***What***: The rover's Raspberry Pi ("brain") must be able to identify what USB port a microcontroller is plugged into, and what the microcontroller's purpose is (eg. arm vs left drivetrain vs right drivetrain).

***Why***: To prevent having to hard-code COM ports (which can often change), and to allow the brain to send messages only to the intended microcontroller.

***Where***: Create a folder called "Arduino" in the Scheduler's top directory. Work in the [arduino_connection](https://github.com/Uvic-Robotics-Club/Scheduler/tree/arduino_connection) branch.

***Subtasks***:
- [x] Learn how to interface with Arduino
- [x] Learn how USB ports work on the Raspberry Pi
- [x] Write program that identifies the microcontroller
- [x] Test that program works
