### ISSUE TITLE
Implement way for rover to communicate wirelessly

### ISSUE THREAD

**Issue by s-sparrow** [Uvic-Robotics-Club/Shell#14]
***What***: Create a way for the base station and rover schedulers to communicate over wifi (integrating with Scheduler will take place in a future issue).

***Why***: So that rover can be controlled remotely.

***Where***: Put code in a ['Networking' directory](https://github.com/Uvic-Robotics-Club/Scheduler/tree/Networking-Module/Networking) in the Scheduler. Work in [Networking-Module](https://github.com/Uvic-Robotics-Club/Scheduler/tree/Networking-Module) branch.

***Subtasks***:
- [x] Create client file
- [x] Create server file
- [ ] Code review changes with @s-sparrow
