### ISSUE TITLE
Research Github Wikis and Pages

### ISSUE THREAD

**Issue by s-sparrow** [Uvic-Robotics-Club/Shell#16]
***What***: Learn about and create some Wiki pages for Scheduler documentation, coding standards, github examples, tutorial-issue templates, and CIRC competition background. These pages don't necessarily need to be filled in yet.

***Why***: To create a place where developers can check for club documentation. Readme files are fine initially, but as the Scheduler documentation grows, we will find that it is better to have it split up into headings in a Wiki. Detailed messages that are sent on Slack can also be put into the readme, such as the CIRC competition summary.

***Where***: This will be determined after leaning about how github Wikis work. We may need to consider Github pages instead, if we don't want to always have the Wiki tied to a repository.

***Subtasks***:
- [x] Learn how Github Wikis work
- [x] Learn how Github Pages work
- [x] Gather and group information that we would want kept on these sites
- [x] Create Wikis/Pages
- [x] Fill in existing documentation
- [x] Update Readme's to reference the Wiki

**Comment by s-sparrow** [comment]
I will need to talk to Greg about the archived Administrative repository.
