### ISSUE TITLE
Implement way to receive and encode webcam images

### ISSUE THREAD

**Issue by s-sparrow** [Uvic-Robotics-Club/Shell#17]
***What***: Implement a program that can receive webcam data, take a single image and encode it in way that can be sent over a network.

***Why***: To provide us with a way to get a live stream of images from the rover's webcam to eventually be sent to the base station. This issue does not involve integrating this functionality into the scheduler or setting up a network. Those tasks will be done in a future issue, which will depend on the research/work created in this issue.

***Where***: Create a branch in the [Scheduler](https://github.com/Uvic-Robotics-Club/Scheduler) repository and name it "Camera". Then switch into that branch, and create a folder called "Camera" in the Scheduler's root directory.

***Subtasks***:
- [x] Look at opencv-python library and examples
- [x] Set up webcam to receive and display video feed on a laptop
- [x] Research the necessary functions that opencv-python has available for encoding data to be sent over a network.
- [x] Implement a program that will receive an image, encode it, and then decode it.
- [x] Create a README.md file in Camera folder that mentions any libraries that need to be installed and what version is necessary (for instance, what version of opencv-python is used)
- [x] Document any extra setup in the README that is needed to connect the webcam to a computer (there might be none).

**Comment by JoshuaGabriel** [comment]
https://github.com/Uvic-Robotics-Club/Scheduler/tree/Camera
