### ISSUE TITLE
Design layout for runt rover

### ISSUE THREAD

**Issue by s-sparrow** [Uvic-Robotics-Club/Shell#19]
***What***: Come up with a design that will let us put the battery, voltage regulator, breadboard with motordrivers and UNO, Raspberry Pi, USB power bank, and webcam all on the runt rover's body. The design will eventually be implemented by the Mechanical team through 3D printing and other methods. The two main goals are to prevent components from falling off of the rover while it is moving, and to allow for the components to be removed if necessary. For example, the battery will need to be removable to be charged, and the Raspberry Pi will need to be removable so that someone can work on it at home.

***Why***: To provide a design that will create a sturdy system for developers to test software on. It should also look good and clean, so that we can show it off at club events.

***Where***: Share design ideas and files with @s-sparrow over Slack and during weekly meetings. The files can eventually be put on our Google Drive.

***Subtasks***:
- [x] Get any info and measurements regarding components that you are not familiar with (power bank, webcam, etc.).
- [x] Come up with initial ideas for the rover's layout and try them out
- [x] Draft up some examples and verify with @s-sparrow that nothing is missing.
- [x] Draft up ideas for individual components. For example, what will hold the Raspberry Pi in place?

**Comment by s-sparrow** [comment]
This issue will be assigned to Corny when he joins our Github organization.
