### ISSUE TITLE
Implement a database for error logs

### ISSUE THREAD

**Issue by s-sparrow** [Uvic-Robotics-Club/Shell#20]
***What***: Implement a script containing SQL commands that will create a database that will be kept on the base station and will hold errors that are reported by the rover. The database should have three sections: time logged, component that logged the issue, and error message.

***Why***: To have a place where the rover operator can check reported errors.

***Where***: In the [Scheduler](https://github.com/Uvic-Robotics-Club/Scheduler) repository, create a folder called 'Database' and put the script in there.

***Subtasks***:
- [ ] Learn about databases
- [ ] Learn how to create tables with SQL commands
- [ ] Create a text file that contains SQL commands to create a table
