### ISSUE TITLE
Implement a MongoDB database for sensors

### ISSUE THREAD

**Issue by s-sparrow** [Uvic-Robotics-Club/Shell#24]
***What***: Implement functions to create a MongoDB database and insert two types of sensor data.

***Why***: To have a place to store all the data that is sent from sensors located on the Rover. The plan is to have the Rover contain various sensors, such as a thermometer, which will then send data back to the Base Station. The Base Station scheduler will then pass this data to a MongoDB database, which will store the sensor data and time/date. Then, the Rover operator can manually view the data in the database, or the data can be displayed on the Base Station GUI in real-time.

***Where***: In the Scheduler's [MongoDB_files branch](https://github.com/Uvic-Robotics-Club/Scheduler/tree/MongoDB_files), create a folder called 'Sensor Database' and put all database files in there.

***Subtasks***:
- [ ] Learn about MongoDB
- [ ] Create a Python class SensorDatabase and put it inside sensor_database.py.
- [ ] Put the pymongo.MongoClient() function call in the class constructor. For now, we can store the MongoDB client as a SensorDatabase class variable.
- [ ] Write a function create_table() which will run any necessary commands to set up the database structure we need. For example, let's start by assuming we have 2 sensors, so create 1 collection per sensor. Assume that sensor 1 values are floats. (e.g. 1.234). Assume that sensor 2 values are input as a list of 3 floats (e.g. [1.234, 2.345, 3.456]). We would also like the time/date to be stored with each sensor value.
- [ ] Look into how to get and store time/date info into MongoDB
- [ ] Write a function add_sensor_1_data(sensor) which will take in a float 'sensor' and add it as an entry in the sensor 1 collection. Store the time/date as well.
- [ ] Write a function add_sensor_2_data(sensor) which will take in a list of 3 floats and add them as an entry in the sensor 2 collection. Store the time/date as well.
- [ ] Verify add_sensor_1_data() and add_sensor2_data() by passing in a couple of inputs and validate that they properly inserted into the database
- [ ] Create a file test_data.txt which includes a list of floats (for example, 1000 random floats). You can generate this file with a python script and the random.py library. It can be formatted in whatever way is easiest for you to work with (csv, one value per line, etc).
- [ ] Create a function test_sensor_1(filename) which will read in the floats from filename (i.e. test_data.txt) and will call add_sensor_1_data() on each value.
- [ ] Time how long it takes to insert the 1000 values. If possible, check how large database gets.

**Comment by s-sparrow** [comment]
If you feel like a single MongoDB collection would be more suitable for storing values from multiple sensors, then you are free to do that instead as long as we can still retrieve values from one sensor at a time.
