### ISSUE TITLE
Improve scheduler

### ISSUE THREAD

**Issue by s-sparrow** [Uvic-Robotics-Club/Shell#6]
***What***: Fix known-issues with the scheduler.

***Why***: To make the scheduler more robust.

***Where***: Modify any scheduler files necessary and use [threading_improvements](https://github.com/Uvic-Robotics-Club/Scheduler/tree/threading_improvements) branch.

***Subtasks***:
- [ ] No reserved threads for high priority tasks (if they're all running slow low priority tasks, it effectively locks it)
- [ ] Incomplete type-checking on return values (I'm not sure how far I got here. The intent was for it to take either a pq object, or a list of pq objects)
- [ ] Threads freezing indefinitely and locking that thread of the scheduler. Enough freeze, and it no longer works (This can be fixed by putting some sort of timeout in the thread runners) (related - people using sleeps in their code instead of properly returning control to the scheduler)
- [ ] Something spamming the priority queue with a bunch of the same thing. This could have a variety of sources - links that lead into a loop, incorrect/missing "how often to update" logic, etc...
- [ ] Other objects using multi-threading and interfering with its thread count
